### ISSUE TITLE
Can you fix the issue in new update 2.9.0

### ISSUE THREAD

**Issue by iamnishantgaharwar** [Sean-Bradley/R3F-Pack#10]
I don't know how i did that but there is an error which is not letting it create build file here is the updated code for r3f-pack.js. I just don't wanted to create a pr for one line of code. 

`cpy "public/**" build/${getFormattedDate()} && webpack --config ./node_modules/r3f-pack/bin/webpack.prodByDate.js`

After updating the code. Super Clean

![image](https://github.com/user-attachments/assets/be5281b6-95b3-4da4-a500-7c3b4dd1d456)

**Comment by Sean-Bradley** [comment]
done. 
Now v2.9.1
