### ISSUE TITLE
Ability to proxy for development purposes

### ISSUE THREAD

**Issue by Netrunner-A** [Sean-Bradley/R3F-Pack#11]
One feature I missed after upgrading to R3F was the ability to add a "proxy" entry to package.json and have all calls directed to it.

https://create-react-app.dev/docs/proxying-api-requests-in-development/

For example,
package.json:
```js
{
// code...
"proxy": "http://localhost:3001",  
// code...
}
```

example.jsx:
```JavaScript
// code..
fetch("/api/getData")
// code ...
```

The fetch call will call `http://localhost:3001/api/getData`, instead of `http://localhost:3000/api/getData`.
This allows you to setup for example a testing express server on 3001, while keeping the client code the same after building and deploying to a production environment without the proxy.

**Comment by Sean-Bradley** [comment]
I use a proxy in this r3f demo.

https://github.com/Sean-Bradley/BirdMMO

See ./src/client/webpack.dev.js

**Comment by Netrunner-A** [comment]
Thank you for your prompt response,

The demo is really helpful, thanks. And I guess that react-scripts functionality was only a convenience.

**Comment by Sean-Bradley** [comment]
both react-scripts and r3f use webpack under the hood.
I need to think for a while about adding the proxy option to r3f-pack.
