### ISSUE TITLE
node\r no such file or directory

### ISSUE THREAD

**Issue by ChrisAB** [Sean-Bradley/R3F-Pack#12]
Library installed from npm installs with DOS line terminations instead of Unix line terminations which causes
"node\r no such file or directory"
On Unix systems.

**Comment by Sean-Bradley** [comment]
I fixed this many versions ago, but I seem to have broken it again.
I have now added a `.gitattributes` that sets `*.js` to have LF line endings.
Give it a try. `v3.0.7`

```bash
npm install r3f-pack@latest
```

**Comment by Sean-Bradley** [comment]
I tested a repo on Ubuntu 24.04 that uses the latest R3F-Pack and it works

```
git clone https://github.com/Sean-Bradley/React-Three-Fiber-Boilerplate.git
cd React-Three-Fiber-Boilerplate
npm install
npm start
```

So closing.
