### ISSUE TITLE
Error in mac: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by YJH1993** [Sean-Bradley/R3F-Pack#2]
It will shows "env: node\r: No such file or directory" after run start command,
Any suggestion to fix this error?

**Comment by Sean-Bradley** [comment]
It is written exactly the same as from react-scripts
https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/bin/react-scripts.js#L1

can your describe your development environment

**Comment by YJH1993** [comment]
in react-scripts.js, the line break is LF, which is workable for Linux,
but in r3f-pack.js, the line break is CRLF, which will occur this error.

**Comment by Sean-Bradley** [comment]
ok, so when you added the space, it then worked for you?

**Comment by YJH1993** [comment]
i save the file with LF, and it works. nothing related to the space i think.

**Comment by Sean-Bradley** [comment]
Ok, I have figured this out my side. Thanks for spotting it,
I will push it in a moment.

**Comment by Sean-Bradley** [comment]
I have pushed some updates to [r3f-pack](https://github.com/Sean-Bradley/R3F-Pack) and [new-cra](https://github.com/Sean-Bradley/new-cra) to change CLRF to LF
I don't have access to a Mac right now, but I tested

`
npx new-cra test-app
`

on 

```text
Ubuntu 23.10
npm 9.2.0
node 18.13.0
```

And it worked.

So try updating r3f-pack in your project now using,
```bash
npm install r3f-pack@latest
```

Starting should then show at least 
`R3F-Pack [2.4.1]`

or if using `new-cra`
```bash
npx new-cra@latest your-app-name
```
`new-cra@1.3.0`

**Comment by YJH1993** [comment]
Thanks, it works with 2.4.1
