### ISSUE TITLE
HotModuleReload + fast refresh is too hasty. any existing way to temporarily turn off fast refresh?

### ISSUE THREAD

**Issue by enigmashot** [Sean-Bradley/R3F-Pack#5]
Hello! 
R3-F pack was an great upgrade from react-scripts and everything works flawlessly. But one change after upgrading to R3f pack is that the hot reload is triggered a way higher number of times. I mean forget waiting till a save, it starts throwing errors the moment i start writing a line of code and keeps refreshing with every keystroke. As you can imagine, it is a detriment to development flow.

I'm not sure if this is the intented effect and the desired behavior- or -if any of the other extensions i am using in VSCode might be contributing to it, but I humbly seek advice in disabling and enabling the fast refresh feature. 

Ideally, I would like the hotModuleReload to trigger once the file is saved. I am not familiar enough with webpack configurations and do not wish to break what is already working.  

Please advice. I appreciate your consideration.

**Comment by Sean-Bradley** [comment]
"the moment i start writing a line of code"
This is not what r3f-pack does. You need to save, or press ctrl-s to see the updates.
You have something else setup in your vscode that is causing your browser to update on keypresses in the IDE.
I use vscode and I cannot reprodue your problem.
I imagine that i'd need to install or configure something extra.

A minimal example of using r3f-pack
```bash
npx new-cra@latest my-app
cd my-app
npm start
```

Or any branch in this repo https://github.com/Sean-Bradley/React-Three-Fiber-Boilerplate

**Comment by enigmashot** [comment]
Thank you for the response. That makes sense. I suspect a vscode extension (maybe for formatting or some other convenience feature) maybe over-enthusiastic with the autosave. with all extensions disabled, the behaviour is as expected.

**Comment by Sean-Bradley** [comment]
Cool. Leave a comment if you find out what caused it.

**Comment by enigmashot** [comment]
It was just the VsCode Autosave feature. The autosave feature was set to 'after delay' and the delay got changed to 100ms for some reason and that's what was triggering the HMR. 

R3f-Pack has been flawless though.. thanks again for maintaining it. Makes it a lot easier for beginners.
