### ISSUE TITLE
Does not support process.env

### ISSUE THREAD

**Issue by gyanverma2** [Sean-Bradley/R3F-Pack#6]
Hi
Thanks for your great script.
I was wondring how to add process.env support into this script.

With react-script it comes by default without any new setup.

Thanks

**Comment by cohenrobinson** [comment]
Use `dotenv-webpack`. You'll just have to edit the webpack config per the instructions and this will replace the standard react-script function.

Ultimately, I believe the intent with `R3F-Pack` is to be as lightweight as possible, which means that the standard defaults may not come with it.

https://github.com/mrsteele/dotenv-webpack

**Comment by Sean-Bradley** [comment]
I am wary about adding too much fuctionality. But I have now added the [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack) lib as suggested above.

To get latest r3f-pack (2.7.2)

```
npm install r3f-pack@latest    
```

Then, in your project root, add a `.env` file.

E.g.,
```text
// .env
some_env_variable=ABcdEFgh
```

And you can use it in your scripts

```jsx
import { createRoot } from 'react-dom/client'

console.log(process.env.some_env_variable)

createRoot(document.getElementById('root')).render(
  <div>some_env_variable = {process.env.some_env_variable}</div>
)
```

**Comment by gyanverma2** [comment]
Thanks alot for the update. It make this package perfect and replacable to react-script easily without any other changes.
